### ISSUE TITLE
CSS issue on /gamepage/:username

### ISSUE THREAD

**Issue by super9user** [yousuf031991/HumanAgentInteraction#16]
<img width="1210" alt="screen shot 2017-02-09 at 5 08 48 pm" src="https://cloud.githubusercontent.com/assets/12291057/22808766/e24456f2-eeea-11e6-926d-404a34b2e6d7.png">

Font of navbar gets smaller on this URL as compared to navbar on other URLS

**Comment by yousuf031991** [comment]
I think this is fixed

**Comment by tgomudur** [comment]
Resolved with latest commit
