### ISSUE TITLE
Manage Admin validation

### ISSUE THREAD

**Issue by yousuf031991** [yousuf031991/HumanAgentInteraction#29]
Can we use a bootstrap modal instead of a confirm pop up? If you prevent the page from creating additional dialogs, you can't delete any more admins.
Also, the success message section in the right panel should be inside the panel div. It's currently coming out of the div.
![image](https://cloud.githubusercontent.com/assets/9531811/23146788/20585150-f797-11e6-83d4-c17be78c8481.png)

**Comment by adityab17190** [comment]
I had thought about it. But considering that the admins won't be deleted on a frequent basis, I decided to go for default confirm box.  But if everyone feels bootstrap modal is necessary, I can add it.
